# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - PostgresPreview


pool:
   vmImage: ubuntu-latest

variables:
- group: REDGATE
# Where the flyway.conf file resides for your project
- name: FLYWAY_CONFIG_FILES
  value: $(Build.Repository.LocalPath)/PostgresPreviewRepo/PostgresPreview/flyway.conf
# Where where your flyway migrations reside in your project
- name: FLYWAY_LOCATIONS
  value: $(Build.Repository.LocalPath)/PostgresPreviewRepo/PostgresPreview/migrations
# Where where your flyway reports reside in your project
- name: FLYWAY_REPORTS
  value: $(Build.Repository.LocalPath)/reports

stages:
- stage: 'Deploy'
  displayName: Database Deployment
  jobs:
  - job: DeployToProd
    steps:
# Ideally we should have a task that compares Acceptance with Prod to ensure they are at the same version
    - download: current
      artifact: Flyway-migrations
    - task: CmdLine@2
      displayName: ls-pipeline-workspace-folder
      inputs:
        script: "ls $(Pipeline.Workspace)"
    - task: CmdLine@2
      displayName: Flyway info (pre-deployment)
      inputs:
        script: "docker run --rm -v $(Pipeline.Workspace)/Flyway-migrations:/flyway/sql flyway/flyway info 
        -schemas=dbo 
        -user=spawn_admin_YOsj -password=Xg6T6EkL7AdFBW5T 
        -url='dbc:postgresql://rbxtmzu7.instances.spawn.cc:30330/pagila 



