# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include: 
    - ADAMBRITTRG/PostgresPreviewRepo
 
pool:
  vmImage: 'ubuntu-latest'

variables:
- group: POSTGRES_VARIABLE_GROUP
# Where the flyway.conf file resides for your project
- name: FLYWAY_CONFIG_FILES
  value: $(Build.Repository.LocalPath)/PostgresPreviewRepo/PostgresPreview/flyway.conf
# Where where your flyway migrations reside in your project
- name: FLYWAY_LOCATIONS
  value: $(Build.Repository.LocalPath)/PostgresPreviewRepo/PostgresPreview/Migrations


stages:
- stage: "CI"
  displayName: "Database CI"
  jobs:
  - job: Static_Analysis
    displayName: SQL static analysis (uses SQLFluff)
    steps:
    - task: PublishPipelineArtifact@1
      displayName: Publish Build Artifacts
      inputs:
        targetPath: '$(Build.Repository.LocalPath)/sqlserver/StackOverflow2010/migrations'
        artifact: Flyway-migrations
        publishLocation: 'pipeline'


stages:
- stage: Deploy
  displayName: Database Deployment
  jobs:
  - job: DeployToProd
    steps:
# Ideally we should have a task that compares Acceptance with Prod to ensure they are at the same version
    - download: current
      artifact: Flyway-migrations
    - task: CmdLine@2
      displayName: ls-pipeline-workspace-folder
      inputs:
        script: "ls $(Pipeline.Workspace)"
    - task: CmdLine@2
      displayName: Flyway info (pre-deployment)
      inputs:
        script: "docker run --rm -v $(Pipeline.Workspace)/Flyway-migrations:/flyway/sql flyway/flyway migrate
        -outOfOrder=true -schemas=dbo 
        -user=$(QA_USER) -password=$(QA_PASSWORD) 
        -url='$(QA_URL)'
        -licenseKey=$(FLYWAY_LICENSE_KEY)"