# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include: 
    - ADAMBRITTRG/PostgresPreviewRepo
 
pool:
  vmImage: 'ubuntu-latest'
 
steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
  displayName: 'Install Docker'
 
- task: CmdLine@2
  displayName: Migrate scripts to the pre-production environment
  inputs:
    targettype: 'inline'
    script: "docker run -v flyway/flyway migrate -schemas=public -url=jdbc:postgresql://rbxtmzu7.instances.spawn.cc:30330/pagila -user=spawn_admin_YOsj -password=Xg6T6EkL7AdFBW5T

#    - task: CmdLine@2
#      displayName: Run all migrations on a clean database
#      inputs:
#        script: "docker run --rm -v $(FLYWAY_LOCATIONS):/flyway/sql flyway/flyway clean migrate 
#        -schemas=dbo 
#        -user=$(STACKOVERFLOW2010_TEMP_USER) -password=$(STACKOVERFLOW2010_TEMP_PASSWORD) 
#        -url='$(STACKOVERFLOW2010_TEMP_URL)'
#        -licenseKey=$(FLYWAY_LICENSE_KEY)"