# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
   vmImage: ubuntu-latest

steps:
  - task: CmdLine@2
    displayName: Validate Migrate Scripts
    inputs:
      script: 'flyway migrate info -url=jdbc:postgresql://rbxtmzu7.instances.spawn.cc:30330/pagila -user=spawn_admin_YOsj -password=Xg6T6EkL7AdFBW5T'
      workingDirectory: ADAMBRITTRG/PostgresPreviewRepo
      failOnStderr: true
  - task: CmdLine@2
    displayName: Validate Undo Scripts
    inputs:
      script: 'flyway undo info -url=url=jdbc:postgresql://rbxtmzu7.instances.spawn.cc:30330/pagila -user=spawn_admin_YOsj -password=Xg6T6EkL7AdFBW5T'
      workingDirectory: ADAMBRITTRG/PostgresPreviewRepo
      failOnStderr: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: PostgrePreviewRepo-Build'
    inputs:
      PathtoPublish: ADAMBRITTRG/PostgresPreviewRepo
      ArtifactName: PostgrePreviewRepo-Build

