# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

task: CmdLine@2
      displayName: Flyway info (pre-deployment)
      inputs:
        script: "docker run --rm flyway/flyway-azure:latest-alpine flyway -schemas=public -outOfOrder="true" -teams -LicenseKey="FL0100472D9B91AE28CDF25744EE55FFB14E09C51683FF0BAB4BE29FCDA61B3477DCC35CB64A29E5C4249908F408D77C66D6FB4CC0C61C8FF0E22A4B28961901D93EC6F355AB9AC350EDB8A6B77EC5266DDE70FDF9EF5AC15E3EB5B21D1278CEE6C5DFDB34413A08ADC95E23E9FDDF30EC914C96B75565039745A60362889D0B2536BB83AF249C328C8307E43C2E8A68D9C1D0D9CD543AEC6F13A14F4F76B1F22530852991C4188E09E9B1D19EFCF0DA9F2D111E6B2C4AA6AF636ABDE95025C29534EE8E1A8E7B9A09CF360C6B3B5BC44F7F6C3AD9F48A6D7A95E35073A103E6398A757864056F3F0C8C2600E10C57223F35DF4F85F8C8B257238D1A3BB841053D8E" -ignoreMigrationPatterns="versioned:missing" -url= jdbc:postgresql://rbxtmzu7.instances.spawn.cc:30038/pagila -user= spawn_admin_cBuT -password= IxZPZTxf2aXJmfbq migrate
