name: 'Migrate database schema'

on:
  push:
    branches:
      - main

jobs:
  migrate-database:
    name: Run Flyway migrations
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - run: >-
          docker run --rm
          --volume ${{ github.workspace }}/migrations:/flyway/sql:ro
          flyway/flyway
          -url="jdbc:postgresql://${{ secrets.DB_PROD_URL }}?sslmode=require"
          -user="${{ secrets.DB_PROD_URL }}"
          -password="${{ secrets.DB_PROD_USER }}"
          migrate
