name: 'Migrate database schema'

on:
  push:
    branches:
      - main
      
      
env:
    DB_PROD_URL: jdbc:postgresql://rbxtmzu7.instances.spawn.cc:32671/pagila
    DB_PROD_USER: spawn_admin_cBuT
    DB_TEMP_URL: jdbc:postgresql://rbxtmzu7.instances.spawn.cc:30022/pagila
    DB_TEMP_USER: spawn_admin_cBuT
    FLYWAY_EDITION: enterprise
    FLYWAY_LOCATIONS: ${{ github.workspace }}/PostgresPreview/migrations
    FLYWAY_PROJECT_PATH: postgresql/pagila
    SQLFLUFF_DIALECT: postgres
      
jobs:

  build-database:
    name: build database
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      - run: >-
          docker run --rm
          --volume ${{ github.workspace }}/PostgresPreview/migrations:/flyway/sql:ro
          flyway/flyway
          -url="${{ env.DB_TEMP_URL }}"
          -user="${{ env.DB_TEMP_USER }}"
          -password="${{ secrets.DB_TEMP_PASSWORD }}"
          repair
      - run: >-
          docker run --rm
          --volume ${{ github.workspace }}/PostgresPreview/migrations:/flyway/sql:ro
          flyway/flyway
          -url="${{ env.DB_TEMP_URL }}"
          -user="${{ env.DB_TEMP_USER }}"
          -password="${{ secrets.DB_TEMP_PASSWORD }}"
          clean migrate
      - run: >-
          docker run --rm
          --volume ${{ github.workspace }}/PostgresPreview/migrations:/flyway/sql:ro
          flyway/flyway
          -url="${{ env.DB_TEMP_URL }}"
          -user="${{ env.DB_TEMP_USER }}"
          -password="${{ secrets.DB_TEMP_PASSWORD }}"
          info

  migrate-database:
    name: Run Flyway migrations
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - run: >-    
          docker run --rm
          --volume ${{ github.workspace }}/PostgresPreview/migrations:/flyway/sql:ro
          flyway/flyway
          -url="${{ env.DB_PROD_URL }}"
          -user="${{ env.DB_PROD_USER }}"
          -password="${{ secrets.DB_PROD_PASSWORD }}"
          info
      - run: >-
          docker run --rm
          --volume ${{ github.workspace }}/PostgresPreview/migrations:/flyway/sql:ro
          flyway/flyway
          -url="${{ env.DB_PROD_URL }}"
          -user="${{ env.DB_PROD_USER }}"
          -password="${{ secrets.DB_PROD_PASSWORD }}"
          migrate
      - run: >-
          docker run --rm
          --volume ${{ github.workspace }}/PostgresPreview/migrations:/flyway/sql:ro
          flyway/flyway
          -url="${{ env.DB_PROD_URL }}"
          -user="${{ env.DB_PROD_USER }}"
          -password="${{ secrets.DB_PROD_PASSWORD }}"
          info
